from src.company_item import CompanyItem
from src.scrapers import Scrapers


def get_company_list() -> list[CompanyItem]:
    return [
        CompanyItem("archblock", "https://jobs.lever.co/archblock", Scrapers.LEVER, "https://www.archblock.com"),
        CompanyItem('smart-token-labs', 'https://apply.workable.com/smart-token-labs', Scrapers.WORKABLE,
                    'https://smarttokenlabs.com'),
        CompanyItem('superfluid', 'https://apply.workable.com/superfluid/#jobs', Scrapers.WORKABLE,
                    'https://www.superfluid.finance'),
        CompanyItem("request", "https://jobs.lever.co/request", Scrapers.LEVER, "https://request.network"),
        CompanyItem('mina-foundation', 'https://apply.workable.com/mina-foundation', Scrapers.WORKABLE,
                    'https://www.minafoundation.com'),
        CompanyItem('BlockSwap', 'https://jobs.lever.co/BlockSwap', Scrapers.LEVER, 'https://www.blockswap.network'),
        CompanyItem('ultra', 'https://jobs.lever.co/ultra', Scrapers.LEVER, 'https://ultra.io'),
        CompanyItem('glassnode', 'https://jobs.lever.co/glassnode', Scrapers.LEVER, 'https://glassnode.com'),
        CompanyItem('dappradar', 'https://dappradar.bamboohr.com/careers', Scrapers.BAMBOOHR,
                    'https://dappradar.com'),
        CompanyItem('web3', 'https://web3.bamboohr.com/careers', Scrapers.BAMBOOHR, 'https://web3.foundation'),
        CompanyItem('protocollabs', 'https://boards.greenhouse.io/protocollabs', Scrapers.GREENHOUSE,
                    'https://protocol.ai/about'),
        CompanyItem('Boost', 'https://jobs.ashbyhq.com/Boost', Scrapers.ASHBYHQ, 'https://Boost.xyz'),
        CompanyItem('exponential', 'https://jobs.ashbyhq.com/exponential', Scrapers.ASHBYHQ, 'https://exponential.fi'),
        CompanyItem('pyth', 'https://jobs.ashbyhq.com/pythnetwork', Scrapers.GREENHOUSE,
                    'https://pyth.network'),
        CompanyItem('outlierventures', 'https://outlierventures.bamboohr.com/careers', Scrapers.BAMBOOHR,
                    'https://outlierventures.io'),
        CompanyItem("subspacelabs", "https://jobs.lever.co/autonomys", Scrapers.LEVER,
                    "https://www.autonomys.xyz"),
        CompanyItem("biconomy", "https://jobs.lever.co/biconomy", Scrapers.LEVER, "https://www.biconomy.io"),
        CompanyItem('coinmetrics', 'https://boards.greenhouse.io/coinmetrics', Scrapers.GREENHOUSE,
                    'https://coinmetrics.io'),
        CompanyItem('goldsky', 'https://boards.greenhouse.io/goldsky', Scrapers.GREENHOUSE,
                    'https://goldsky.com'),
        CompanyItem('iofinnet', 'https://iofinnethr.bamboohr.com/jobs/?source=bamboohr', Scrapers.BAMBOOHR,
                    'https://www.iofinnet.com'),
        CompanyItem('filecoinfoundation', "https://boards.greenhouse.io/filecoinfoundation", Scrapers.GREENHOUSE,
                    "https://fil.org"),
        CompanyItem('econetwork', 'https://job-boards.greenhouse.io/ecoinc', Scrapers.GREENHOUSE,
                    'https://eco.com'),
        CompanyItem('obol-tech', 'https://jobs.lever.co/obol-tech', Scrapers.LEVER, 'https://obol.tech'),
        CompanyItem("coinlist", "https://apply.workable.com/coinlist", Scrapers.WORKABLE, "https://coinlist.co"),
        CompanyItem('distributedcrafts', 'https://apply.workable.com/distributedcrafts', Scrapers.WORKABLE,
                    'https://www.gobob.xyz/'),
        CompanyItem('prepo', 'https://apply.workable.com/prepo', Scrapers.WORKABLE,
                    'https://prepo.io'),
        CompanyItem("nimbus", "https://job-boards.greenhouse.io/nimbus", Scrapers.GREENHOUSE,
                    "https://free.technology/nimbus"),
        CompanyItem("messari", "https://boards.greenhouse.io/messari", Scrapers.GREENHOUSE, "https://messari.io"),
        CompanyItem('shadow', 'https://jobs.ashbyhq.com/shadow', Scrapers.ASHBYHQ,
                    'https://www.shadow.xyz'),
        CompanyItem('flipsidecrypto', 'https://jobs.ashbyhq.com/flipsidecrypto', Scrapers.ASHBYHQ, 'https://flipsidecrypto.xyz'),
        CompanyItem('blast', 'https://jobs.ashbyhq.com/blast-io', Scrapers.ASHBYHQ, 'https://blast.io'),
        CompanyItem('dydx', 'https://boards.greenhouse.io/dydx', Scrapers.GREENHOUSE,
                    'https://dydx.exchange'),
        CompanyItem('multiversx', 'https://jobs.lever.co/multiversx', Scrapers.LEVER, 'https://multiversx.com'),
    ]
