
from src.company_item import CompanyItem
from src.scrapers import Scrapers


def get_company_list() -> list[CompanyItem]:
    return [
        CompanyItem("base", "https://www.base.org/jobs", Scrapers.BASE.value, "https://www.base.org"),
        CompanyItem('Numeus', 'https://job-boards.eu.greenhouse.io/numus', Scrapers.GREENHOUSE.value, 'https://classic.numeus.xyz'),
        CompanyItem("kraken", "https://jobs.ashbyhq.com/kraken.com", Scrapers.ASHBYHQ.value, "https://kraken.com"),
        CompanyItem('fireblocks', 'https://job-boards.greenhouse.io/fireblocks', Scrapers.GREENHOUSE.value, 'https://www.fireblocks.com'),
        CompanyItem('moonpay', 'https://jobs.lever.co/moonpay', Scrapers.LEVER.value, 'https://www.moonpay.com'),
        CompanyItem('phantom', 'https://jobs.ashbyhq.com/phantom', Scrapers.ASHBYHQ.value, 'https://phantom.com'),
        CompanyItem('arbitrumfoundation', 'https://jobs.lever.co/arbitrumfoundation', Scrapers.LEVER.value,
                    'https://arbitrum.foundation'),
        CompanyItem('aragon', 'https://jobs.lever.co/aragon', Scrapers.LEVER.value, 'https://aragon.org'),
        CompanyItem('omni-network', 'https://job-boards.greenhouse.io/omnifdn', Scrapers.GREENHOUSE.value,
                    'https://omni.network'),
        CompanyItem('Tenderly', 'https://jobs.lever.co/Tenderly', Scrapers.LEVER.value, 'https://tenderly.co'),
        CompanyItem('nomic.foundation', 'https://jobs.ashbyhq.com/nomic.foundation', Scrapers.ASHBYHQ.value,
                    'https://nomic.foundation'),
        CompanyItem("binance", "https://jobs.lever.co/binance", Scrapers.LEVER.value, "https://www.binance.com"),
        CompanyItem('ethglobal', 'https://jobs.ashbyhq.com/ethglobal', Scrapers.ASHBYHQ.value, 'https://ethglobal.com'),
        CompanyItem('li.fi', 'https://jobs.ashbyhq.com/li.fi', Scrapers.ASHBYHQ.value, 'https://li.fi'),
        CompanyItem('Caldera', 'https://jobs.ashbyhq.com/Caldera', Scrapers.ASHBYHQ.value, 'https://www.caldera.xyz'),
        CompanyItem('blox-route', 'https://jobs.lever.co/blox-route', Scrapers.LEVER.value,
                    'https://bloxroute.com'),
        CompanyItem('multiversx', 'https://jobs.lever.co/multiversx', Scrapers.LEVER.value, 'https://multiversx.com'),
        CompanyItem('sprucesystems', 'https://jobs.lever.co/sprucesystems', Scrapers.LEVER.value, 'https://spruceid.com'),
        CompanyItem("scroll", "https://job-boards.greenhouse.io/scrollio", Scrapers.GREENHOUSE.value,
                    "https://scroll.io"),
        CompanyItem('impossiblecloud', 'https://jobs.lever.co/impossiblecloud', Scrapers.LEVER.value,
                    'https://www.impossiblecloud.com'),
        CompanyItem('ether-fi', 'https://jobs.ashbyhq.com/ether.fi', Scrapers.ASHBYHQ.value, 'https://www.ether.fi'),
        CompanyItem('fuellabs', 'https://jobs.lever.co/fuellabs', Scrapers.LEVER.value, 'https://www.fuel.network'),
        CompanyItem('harmony', 'https://jobs.lever.co/harmony', Scrapers.LEVER.value, 'https://www.harmony.one'),
        CompanyItem('wintermute', 'https://jobs.lever.co/wintermute-trading', Scrapers.LEVER.value,
                    'https://www.wintermute.com'),
        CompanyItem('coinspaid', 'https://jobs.eu.lever.co/coinspaid', Scrapers.LEVER.value,
                    'https://coinspaid.com'),
        CompanyItem("kaiko", "https://jobs.eu.lever.co/kaiko", Scrapers.LEVER.value, "https://www.kaiko.com"),
        CompanyItem("swissborg", "https://jobs.lever.co/swissborg", Scrapers.LEVER.value, "https://swissborg.com"),
        CompanyItem("ethereumfoundation", "https://jobs.lever.co/ethereumfoundation", Scrapers.LEVER.value,
                    "https://ethereum.org"),
        CompanyItem("aave", "https://jobs.eu.lever.co/avara", Scrapers.LEVER.value, "https://avara.xyz"),
        CompanyItem("crypto", "https://jobs.lever.co/crypto", Scrapers.LEVER.value, "https://crypto.com"),
        CompanyItem("Luxor", "https://jobs.ashbyhq.com/luxor", Scrapers.ASHBYHQ.value, "https://www.luxor.tech"),
        CompanyItem("anchorage", "https://jobs.lever.co/anchorage", Scrapers.LEVER.value, "https://www.anchorage.com"),
        CompanyItem("Polygon", "https://jobs.ashbyhq.com/polygon-labs", Scrapers.ASHBYHQ.value, "https://polygon.technology"),
        CompanyItem('centrifuge', 'https://jobs.lever.co/centrifuge', Scrapers.LEVER.value, 'https://centrifuge.io'),
        CompanyItem("tokenmetrics", "https://jobs.lever.co/tokenmetrics", Scrapers.LEVER.value,
                    "https://www.tokenmetrics.com"),
        CompanyItem("offchainlabs", "https://jobs.lever.co/offchainlabs", Scrapers.LEVER.value,
                    "https://offchainlabs.com"),
        CompanyItem('recall', 'https://job-boards.greenhouse.io/recall', Scrapers.GREENHOUSE.value, 'https://recall.network'),
        CompanyItem("eiger", "https://boards.eu.greenhouse.io/eiger", Scrapers.GREENHOUSE.value,
                    "https://www.eiger.co"),
        CompanyItem('risklabs', 'https://jobs.ashbyhq.com/risklabs', Scrapers.ASHBYHQ.value, 'https://risklabs.foundation'),
        CompanyItem('celestia', 'https://jobs.lever.co/celestia', Scrapers.LEVER.value, 'https://celestia.org'),
        CompanyItem('gauntlet', 'https://jobs.lever.co/gauntlet', Scrapers.LEVER.value, 'https://gauntlet.network'),
        CompanyItem('machinefilab', 'https://jobs.lever.co/machinefilab', Scrapers.LEVER.value, 'https://machinefi.com/lab'),
        CompanyItem('gate.io', 'https://jobs.lever.co/gate', Scrapers.LEVER.value, 'https://gate.io'),
        CompanyItem('auroralabs', 'https://jobs.lever.co/aurora-dev', Scrapers.LEVER.value, 'https://auroralabs.dev'),
        CompanyItem("ledger", "https://jobs.lever.co/ledger", Scrapers.LEVER.value, "https://www.ledger.com"),
        CompanyItem("immutable", "https://jobs.lever.co/immutable", Scrapers.LEVER.value, "https://www.immutable.com"),
        CompanyItem("cere-network", "https://jobs.lever.co/cere-network", Scrapers.LEVER.value, "https://cere.network"),
        CompanyItem('cryptio', 'https://jobs.ashbyhq.com/cryptio', Scrapers.ASHBYHQ.value, 'https://cryptio.co'),
        CompanyItem('matterlabs', 'https://jobs.ashbyhq.com/matter-labs', Scrapers.ASHBYHQ.value, 'https://matter-labs.io'),
        CompanyItem("iftother", "https://boards.greenhouse.io/iftother", Scrapers.GREENHOUSE.value,
                    "https://free.technology"),
        CompanyItem("nimbus", "https://job-boards.greenhouse.io/nimbus", Scrapers.GREENHOUSE.value,
                    "https://free.technology/nimbus"),
        CompanyItem("figure", "https://job-boards.greenhouse.io/figure", Scrapers.GREENHOUSE.value,
                    "https://www.figure.com"),
        CompanyItem("wyndlabs", "https://boards.greenhouse.io/wyndlabs", Scrapers.GREENHOUSE.value,
                    "https://www.wyndlabs.ai"),
        CompanyItem("coinlist", "https://apply.workable.com/coinlist", Scrapers.WORKABLE.value, "https://coinlist.co"),
        CompanyItem('animocabrands', 'https://jobs.lever.co/animocabrands', Scrapers.LEVER.value,
                    'https://www.animocabrands.com'),
        CompanyItem('toku', 'https://jobs.lever.co/toku', Scrapers.LEVER.value, 'https://www.toku.com'),
        CompanyItem("hiro", "https://boards.greenhouse.io/hiro", Scrapers.GREENHOUSE.value, "https://www.hiro.so"),
        CompanyItem('plume', 'https://jobs.ashbyhq.com/plume-network', Scrapers.ASHBYHQ.value, 'https://plume.org'),
        CompanyItem('coingecko', 'https://jobs.lever.co/coingecko', Scrapers.LEVER.value,
                    'https://www.coingecko.com'),
        CompanyItem('connext-network', 'https://jobs.lever.co/connext-network', Scrapers.LEVER.value,
                    'https://www.connext.network'),
        CompanyItem('ethenalabs', 'https://jobs.lever.co/ethenalabs', Scrapers.LEVER.value,
                    'https://www.ethena.fi'),
        CompanyItem('SeiLabs', 'https://jobs.lever.co/SeiLabs', Scrapers.LEVER.value,
                    'https://www.sei.io'),
        CompanyItem('theblock', 'https://jobs.lever.co/theblockcrypto', Scrapers.LEVER.value,
                    'https://www.theblock.co'),
        CompanyItem('bitwise', 'https://jobs.lever.co/bitwiseinvestments', Scrapers.LEVER.value,
                    'https://bitwiseinvestments.com'),
        CompanyItem('grayscaleinvestments', 'https://boards.greenhouse.io/grayscaleinvestments', Scrapers.GREENHOUSE.value,
                    'https://grayscale.com'),
        CompanyItem('dydx', 'https://boards.greenhouse.io/dydx', Scrapers.GREENHOUSE.value,
                    'https://dydx.exchange'),
        CompanyItem('xlabs', 'https://jobs.ashbyhq.com/Xlabs', Scrapers.ASHBYHQ.value,
                    'https://www.xlabs.xyz'),
        CompanyItem('orca', 'https://jobs.ashbyhq.com/orca', Scrapers.ASHBYHQ.value, 'https://www.orca.so'),
        CompanyItem('succinct', 'https://jobs.ashbyhq.com/succinct', Scrapers.ASHBYHQ.value, 'https://succinct.xyz'),
        CompanyItem("jumpcrypto", "https://boards.greenhouse.io/jumpcrypto", Scrapers.GREENHOUSE.value,
                    "https://jumpcrypto.com"),
        CompanyItem("0x", "https://jobs.ashbyhq.com/0x", Scrapers.ASHBYHQ.value, "https://0x.org"),
        CompanyItem("ritual", "https://boards.greenhouse.io/ritual", Scrapers.GREENHOUSE.value,
                    "https://ritual.net"),
        CompanyItem("coinmarketcap", "https://jobs.lever.co/coinmarketcap",
                    Scrapers.LEVER.value, "https://coinmarketcap.com"),
        CompanyItem('orderlynetwork', 'https://job-boards.greenhouse.io/orderly', Scrapers.GREENHOUSE.value,
                    'https://orderly.network'),
        CompanyItem('shardeum', 'https://boards.greenhouse.io/shardeumfoundation', Scrapers.GREENHOUSE.value,
                    'https://shardeum.org'),
        CompanyItem("zora", "https://boards.greenhouse.io/zora", Scrapers.GREENHOUSE.value, "https://zora.co"),
        CompanyItem("wormholefoundation", "https://boards.greenhouse.io/iftother", Scrapers.GREENHOUSE.value,
                    "https://wormhole.com"),
        CompanyItem("blockchain", "https://boards.greenhouse.io/blockchain", Scrapers.GREENHOUSE.value,
                    "https://www.blockchain.com"),
        CompanyItem("OKX", "https://boards.greenhouse.io/OKX", Scrapers.GREENHOUSE.value, "https://okx.com"),
        CompanyItem("bitmex", "https://boards.greenhouse.io/bitmex", Scrapers.GREENHOUSE.value, "https://bitmex.com"),
        CompanyItem("bitgo", "https://boards.greenhouse.io/bitgo", Scrapers.GREENHOUSE.value, "https://bitgo.com"),
        CompanyItem("bitpanda", "https://boards.eu.greenhouse.io/bitpanda", Scrapers.GREENHOUSE.value,
                    "https://bitpanda.com"),
        CompanyItem("uniswaplabs", "https://boards.greenhouse.io/uniswaplabs", Scrapers.GREENHOUSE.value,
                    "https://uniswap.org"),
        CompanyItem('penumbralabs', 'https://boards.greenhouse.io/penumbralabs', Scrapers.GREENHOUSE.value,
                    'https://eco.com'),
        CompanyItem("figment", "https://boards.greenhouse.io/figment", Scrapers.GREENHOUSE.value,
                    "https://www.figment.io"),
        CompanyItem("OpenSea", "https://jobs.ashbyhq.com/OpenSea", Scrapers.ASHBYHQ.value, "https://opensea.io"),
        CompanyItem('center', 'https://jobs.ashbyhq.com/center', Scrapers.ASHBYHQ.value,
                    'https://center.app'),
        CompanyItem('linera.io', 'https://jobs.ashbyhq.com/linera.io', Scrapers.ASHBYHQ.value,
                    'https://linera.io'),
        CompanyItem('shadow', 'https://jobs.ashbyhq.com/shadow', Scrapers.ASHBYHQ.value,
                    'https://www.shadow.xyz'),
        CompanyItem('cointracker', 'https://jobs.ashbyhq.com/cointracker', Scrapers.ASHBYHQ.value,
                    'https://www.cointracker.io'),
        CompanyItem('Bastion', 'https://jobs.ashbyhq.com/Bastion', Scrapers.ASHBYHQ.value,
                    'https://www.bastion.com'),
        CompanyItem('Sui.Foundation', 'https://jobs.ashbyhq.com/Sui%20Foundation', Scrapers.ASHBYHQ.value,
                    'https://sui.io'),
        CompanyItem('dourolabs', 'https://jobs.ashbyhq.com/dourolabs.xyz', Scrapers.ASHBYHQ.value,
                    'https://dourolabs.xyz'),
        CompanyItem('rain', 'https://jobs.ashbyhq.com/rain', Scrapers.ASHBYHQ.value, 'https://www.raincards.xyz'),
        CompanyItem('mystenlabs', 'https://jobs.ashbyhq.com/mystenlabs', Scrapers.ASHBYHQ.value,
                    'https://mystenlabs.com'),
        CompanyItem('conduit', 'https://jobs.ashbyhq.com/Conduit', Scrapers.ASHBYHQ.value, 'https://conduit.xyz'),
        CompanyItem('kiln', 'https://jobs.ashbyhq.com/kiln.fi', Scrapers.ASHBYHQ.value, 'https://www.kiln.fi'),
        CompanyItem("flashbots", "https://jobs.ashbyhq.com/flashbots.net", Scrapers.ASHBYHQ.value,
                    "https://www.flashbots.net"),
        CompanyItem('paradigm.xyz', 'https://jobs.ashbyhq.com/paradigm', Scrapers.ASHBYHQ.value, 'https://www.paradigm.xyz'),
        CompanyItem("solanafoundation", "https://jobs.ashbyhq.com/Solana%20Foundation", Scrapers.ASHBYHQ.value,
                    "https://solana.org"),
        CompanyItem('syndica', 'https://jobs.ashbyhq.com/syndica', Scrapers.ASHBYHQ.value, 'https://syndica.io'),
        CompanyItem('Blockworks', 'https://jobs.ashbyhq.com/Blockworks', Scrapers.ASHBYHQ.value,
                    'https://blockworks.co'),
        CompanyItem('ellipsislabs', 'https://jobs.ashbyhq.com/ellipsislabs', Scrapers.ASHBYHQ.value,
                    'https://ellipsislabs.xyz'),
        CompanyItem('safe.global', 'https://jobs.ashbyhq.com/safe.global', Scrapers.ASHBYHQ.value,
                    'https://safe.global'),
        CompanyItem('Artemisxyz', 'https://jobs.ashbyhq.com/Artemisxyz', Scrapers.ASHBYHQ.value,
                    'https://www.artemis.xyz'),
        CompanyItem('Keyrock', 'https://jobs.ashbyhq.com/Keyrock', Scrapers.ASHBYHQ.value,
                    'https://keyrock.eu'),
        CompanyItem('sound.xyz', 'https://jobs.ashbyhq.com/sound.xyz', Scrapers.ASHBYHQ.value,
                    'https://www.sound.xyz'),
        CompanyItem("quiknodeinc", "https://jobs.ashbyhq.com/quicknode", Scrapers.ASHBYHQ.value,
                    "https://www.quicknode.com"),
        CompanyItem('21co', 'https://job-boards.greenhouse.io/21cotechnologies', Scrapers.GREENHOUSE.value,
                    'https://www.21.co'),
        CompanyItem('mara', 'https://job-boards.greenhouse.io/mara', Scrapers.GREENHOUSE.value,
                    'https://www.mara.com'),
        CompanyItem('xapo', 'https://boards.greenhouse.io/xapo61', Scrapers.GREENHOUSE.value,
                    'https://www.xapobank.com'),
        CompanyItem("exodus54", "https://job-boards.greenhouse.io/exodus54", Scrapers.GREENHOUSE.value,
                    "https://www.exodus.com"),
        CompanyItem("alchemy", "https://boards.greenhouse.io/alchemy", Scrapers.GREENHOUSE.value,
                    "https://www.alchemy.com"),
        CompanyItem("chainalysis", "https://jobs.ashbyhq.com/chainalysis-careers", Scrapers.ASHBYHQ.value,
                    "https://www.chainalysis.com"),
        CompanyItem("magiceden", "https://jobs.ashbyhq.com/magiceden", Scrapers.ASHBYHQ.value,
                    "https://www.magiceden.io"),
        CompanyItem("aztec", "https://boards.eu.greenhouse.io/aztec", Scrapers.GREENHOUSE.value,
                    "https://aztec.network"),
        CompanyItem('near', 'https://job-boards.eu.greenhouse.io/nearfoundation', Scrapers.GREENHOUSE.value,
                    'https://near.org'),
        CompanyItem("nethermind", "https://jobs.ashbyhq.com/nethermind", Scrapers.ASHBYHQ.value,
                    "https://nethermind.io"),
        CompanyItem("dfinity", "https://boards.greenhouse.io/dfinity", Scrapers.GREENHOUSE.value, "https://dfinity.org"),
        CompanyItem('stellar', 'https://jobs.ashbyhq.com/stellar', Scrapers.ASHBYHQ.value, 'https://stellar.org'),
        CompanyItem('bitcoindepot', 'https://job-boards.greenhouse.io/bitcoindepot', Scrapers.GREENHOUSE.value, 'https://bitcoindepot.com'),
        CompanyItem("parity", "https://jobs.ashbyhq.com/parity", Scrapers.ASHBYHQ.value, "https://www.parity.io"),
        CompanyItem("oplabs", "https://jobs.ashbyhq.com/oplabs", Scrapers.ASHBYHQ.value, "https://www.oplabs.co"),
        CompanyItem('walletconnect', 'https://apply.workable.com/reown', Scrapers.WORKABLE.value,
                    'https://reown.com'),
        CompanyItem('distributedcrafts', 'https://apply.workable.com/distributedcrafts', Scrapers.WORKABLE.value,
                    'https://www.gobob.xyz/'),
        CompanyItem('prepo', 'https://apply.workable.com/prepo', Scrapers.WORKABLE.value,
                    'https://prepo.io'),
        CompanyItem('io-global', 'https://apply.workable.com/io-global/#jobs', Scrapers.WORKABLE.value,
                    'https://iohk.io'),
        CompanyItem('clockwork-labs', 'https://apply.workable.com/clockwork-labs',
                    Scrapers.WORKABLE.value, 'https://clockworklabs.io'),
        CompanyItem('o1labs', 'https://boards.greenhouse.io/o1labs', Scrapers.GREENHOUSE.value, 'https://o1labs.org'),
        CompanyItem('paradigm.co', 'https://boards.greenhouse.io/paradigm62', Scrapers.GREENHOUSE.value,
                    'https://www.paradigm.co'),
        CompanyItem("Swissquote", "https://careers.smartrecruiters.com/Swissquote", Scrapers.SMARTRECRUITERS.value,
                    "https://en.swissquote.com"),
        CompanyItem('taxbit', 'https://boards.greenhouse.io/taxbit', Scrapers.GREENHOUSE.value, 'https://taxbit.com'),
        CompanyItem("avalabs", "https://boards.greenhouse.io/avalabs", Scrapers.GREENHOUSE.value,
                    "https://www.avalabs.org"),
        CompanyItem("aptoslabs", "https://boards.greenhouse.io/aptoslabs", Scrapers.GREENHOUSE.value,
                    "https://aptoslabs.com"),
        CompanyItem('almanak', 'https://apply.workable.com/almanak-blockchain-labs-ag', Scrapers.WORKABLE.value,
                    'https://almanak.co'),
        CompanyItem('dune', 'https://jobs.ashbyhq.com/dune', Scrapers.ASHBYHQ.value, 'https://dune.com'),
        CompanyItem('blast', 'https://jobs.ashbyhq.com/blast-io', Scrapers.ASHBYHQ.value, 'https://blast.io'),
        CompanyItem('windranger', 'https://jobs.ashbyhq.com/windranger', Scrapers.ASHBYHQ.value,
                    'https://windranger.io'),
        CompanyItem('foundrydigital', 'https://boards.greenhouse.io/foundrydigital', Scrapers.GREENHOUSE.value,
                    'https://foundrydigital.com'),
        CompanyItem('immunefi', 'https://boards.greenhouse.io/immunefi', Scrapers.GREENHOUSE.value, 'https://immunefi.com'),
        CompanyItem("messari", "https://boards.greenhouse.io/messari", Scrapers.GREENHOUSE.value, "https://messari.io"),
        CompanyItem("serotonin", "https://jobs.lever.co/serotonin", Scrapers.LEVER.value, "https://serotonin.co"),
        CompanyItem("Decentraland", "https://jobs.lever.co/Decentraland", Scrapers.LEVER.value, "https://decentraland.org"),
        CompanyItem("copperco", "https://boards.eu.greenhouse.io/copperco", Scrapers.GREENHOUSE.value,
                    "https://copper.co"),
        CompanyItem("layerzerolabs", "https://boards.greenhouse.io/layerzerolabs", Scrapers.GREENHOUSE.value,
                    "https://layerzero.network"),
        CompanyItem("oasisnetwork", "https://boards.greenhouse.io/oasisnetwork", Scrapers.GREENHOUSE.value,
                    "https://oasisprotocol.org"),
        CompanyItem("ripple", "https://ripple.com/careers/all-jobs", Scrapers.RIPPLE.value, "https://ripple.com"),
        CompanyItem("eigenlabs", "https://jobs.ashbyhq.com/eigen-labs", Scrapers.ASHBYHQ.value,
                    "https://www.eigencloud.xyz"),
        CompanyItem("galaxydigital", "https://boards.greenhouse.io/galaxydigitalservices",
                    Scrapers.GREENHOUSE.value, "https://www.galaxy.com"),
        CompanyItem("clearmatics", "https://job-boards.greenhouse.io/clearmatics", Scrapers.GREENHOUSE.value,
                    "https://www.clearmatics.com"),
        CompanyItem('brave', 'https://job-boards.greenhouse.io/brave', Scrapers.GREENHOUSE.value,
                    'https://brave.com'),
        CompanyItem('zetachain', 'https://job-boards.greenhouse.io/zetachain', Scrapers.GREENHOUSE.value,
                    'https://www.zetachain.com'),
        CompanyItem('coinbase', 'https://www.coinbase.com/careers/positions', Scrapers.COINBASE.value, 'https://coinbase.com')
    ]
