from src.company_item import CompanyItem
from src.scrapers import Scrapers


def get_company_list() -> list[CompanyItem]:
    return [
        CompanyItem("archblock", "https://jobs.lever.co/archblock", Scrapers.LEVER.value, "https://www.archblock.com"),
        CompanyItem('smart-token-labs', 'https://apply.workable.com/smart-token-labs', Scrapers.WORKABLE.value,
                    'https://smarttokenlabs.com'),
        CompanyItem('superfluid', 'https://apply.workable.com/superfluid/#jobs', Scrapers.WORKABLE.value,
                    'https://www.superfluid.finance'),
        CompanyItem("request", "https://jobs.lever.co/request", Scrapers.LEVER.value, "https://request.network"),
        CompanyItem('mina-foundation', 'https://apply.workable.com/mina-foundation', Scrapers.WORKABLE.value,
                    'https://www.minafoundation.com'),
        CompanyItem('BlockSwap', 'https://jobs.lever.co/BlockSwap', Scrapers.LEVER.value, 'https://www.blockswap.network'),
        CompanyItem('ultra', 'https://jobs.lever.co/ultra', Scrapers.LEVER.value, 'https://ultra.io'),
        CompanyItem('glassnode', 'https://jobs.lever.co/glassnode', Scrapers.LEVER.value, 'https://glassnode.com'),
        CompanyItem('dappradar', 'https://dappradar.bamboohr.com/careers', Scrapers.BAMBOOHR.value,
                    'https://dappradar.com'),
        CompanyItem('web3', 'https://web3.bamboohr.com/careers', Scrapers.BAMBOOHR.value, 'https://web3.foundation'),
        CompanyItem("kadena", "https://boards.greenhouse.io/kadenallc", Scrapers.GREENHOUSE.value, "https://kadena.io"),
        CompanyItem('protocollabs', 'https://boards.greenhouse.io/protocollabs', Scrapers.GREENHOUSE.value,
                    'https://protocol.ai/about'),
        CompanyItem('Boost', 'https://jobs.ashbyhq.com/Boost', Scrapers.ASHBYHQ.value, 'https://Boost.xyz'),
        CompanyItem('exponential', 'https://jobs.ashbyhq.com/exponential', Scrapers.ASHBYHQ.value, 'https://exponential.fi'),
        CompanyItem('pyth', 'https://jobs.ashbyhq.com/pythnetwork', Scrapers.GREENHOUSE.value,
                    'https://pyth.network'),
        CompanyItem('outlierventures', 'https://outlierventures.bamboohr.com/careers', Scrapers.BAMBOOHR.value,
                    'https://outlierventures.io'),
        CompanyItem("subspacelabs", "https://jobs.lever.co/autonomys", Scrapers.LEVER.value,
                    "https://www.autonomys.xyz"),
        CompanyItem("biconomy", "https://jobs.lever.co/biconomy", Scrapers.LEVER.value, "https://www.biconomy.io"),
        CompanyItem('coinmetrics', 'https://boards.greenhouse.io/coinmetrics', Scrapers.GREENHOUSE.value,
                    'https://coinmetrics.io'),
        CompanyItem('goldsky', 'https://boards.greenhouse.io/goldsky', Scrapers.GREENHOUSE.value,
                    'https://goldsky.com'),
        CompanyItem('iofinnet', 'https://iofinnethr.bamboohr.com/jobs/?source=bamboohr', Scrapers.BAMBOOHR.value,
                    'https://www.iofinnet.com'),
        CompanyItem("filecoinfoundation", "https://boards.greenhouse.io/filecoinfoundation", Scrapers.GREENHOUSE.value,
                    "https://fil.org"),
        CompanyItem('movementlabs', 'https://jobs.ashbyhq.com/movementlabs', Scrapers.ASHBYHQ.value,
                    'https://movementlabs.xyz'),
        CompanyItem('econetwork', 'https://job-boards.greenhouse.io/ecoinc', Scrapers.GREENHOUSE.value,
                    'https://eco.com'),
        CompanyItem('obol-tech', 'https://jobs.lever.co/obol-tech', Scrapers.LEVER.value, 'https://obol.tech'),
    ]
