from src.company_item import CompanyItem
from src.scrapers import Scrapers


def get_company_list() -> list[CompanyItem]:
    return [
        CompanyItem('anthropic', 'https://job-boards.greenhouse.io/anthropic', Scrapers.GREENHOUSE.value, 'https://www.anthropic.com'),
        CompanyItem('openai', 'https://jobs.ashbyhq.com/openai', Scrapers.ASHBYHQ.value, 'https://openai.com'),
        CompanyItem('groq', 'https://job-boards.greenhouse.io/groq', Scrapers.GREENHOUSE.value, 'https://groq.com'),
        CompanyItem('GPTZero', 'https://jobs.ashbyhq.com/GPTZero', Scrapers.ASHBYHQ.value, 'https://gptzero.me'),
        CompanyItem("perplexityai", "https://job-boards.greenhouse.io/perplexityai", Scrapers.GREENHOUSE.value,
                    "https://www.perplexity.ai"),
        CompanyItem('langchain', 'https://jobs.ashbyhq.com/langchain', Scrapers.ASHBYHQ.value, 'https://www.langchain.com'),
        CompanyItem('Crusoe', 'https://jobs.ashbyhq.com/Crusoe', Scrapers.ASHBYHQ.value, 'https://www.crusoe.ai'),
        CompanyItem('characterai', 'https://jobs.ashbyhq.com/character', Scrapers.ASHBYHQ.value, 'https://character.ai'),
        CompanyItem("cohere", "https://jobs.ashbyhq.com/cohere", Scrapers.ASHBYHQ.value, "https://cohere.com"),
        CompanyItem("reka", "https://jobs.ashbyhq.com/reka", Scrapers.ASHBYHQ.value, "https://www.reka.ai"),
        CompanyItem("sesame", "https://jobs.ashbyhq.com/sesame", Scrapers.ASHBYHQ.value, "https://www.sesame.com"),
        CompanyItem("everai", "https://jobs.ashbyhq.com/everai", Scrapers.ASHBYHQ.value, "https://www.everai.ai"),
        CompanyItem("elevenlabs", "https://jobs.ashbyhq.com/elevenlabs", Scrapers.ASHBYHQ.value, "https://elevenlabs.io"),
        CompanyItem('invisibletech', 'https://job-boards.eu.greenhouse.io/invisibletech', Scrapers.GREENHOUSE.value, 'https://www.invisible.co'),
        CompanyItem('blackforestlabs', 'https://job-boards.greenhouse.io/blackforestlabs', Scrapers.GREENHOUSE.value, 'https://bfl.ai'),
        CompanyItem("mistral", "https://jobs.lever.co/mistral", Scrapers.LEVER.value, "https://mistral.ai"),
        CompanyItem("lovable", "https://jobs.ashbyhq.com/lovable", Scrapers.ASHBYHQ.value, "https://lovable.dev"),
        CompanyItem("eliseai", "https://jobs.ashbyhq.com/eliseai", Scrapers.ASHBYHQ.value, "https://www.eliseai.com"),
        CompanyItem('deepmind', 'https://job-boards.greenhouse.io/deepmind', Scrapers.GREENHOUSE.value, 'https://deepmind.google'),
        CompanyItem('scaleai', 'https://job-boards.greenhouse.io/scaleai', Scrapers.GREENHOUSE.value, 'https://scale.com'),
        CompanyItem('arizeai', 'https://job-boards.greenhouse.io/arizeai', Scrapers.GREENHOUSE.value, 'https://arize.com'),
        CompanyItem('xai', 'https://job-boards.greenhouse.io/xai', Scrapers.GREENHOUSE.value, 'https://x.ai'),
        CompanyItem('neptuneai', 'https://job-boards.greenhouse.io/neptuneai', Scrapers.GREENHOUSE.value, 'https://neptune.ai'),
        CompanyItem("n8n", "https://jobs.ashbyhq.com/n8n", Scrapers.ASHBYHQ.value, "https://n8n.io"),
        CompanyItem("palantir", "https://jobs.lever.co/palantir", Scrapers.LEVER.value, "https://www.palantir.com"),
        CompanyItem("machinify", "https://jobs.ashbyhq.com/machinify", Scrapers.ASHBYHQ.value, "https://www.machinify.com"),
        CompanyItem('assemblyai', 'https://job-boards.greenhouse.io/assemblyai', Scrapers.GREENHOUSE.value, 'https://www.assemblyai.com'),
        CompanyItem('isomorphiclabs', 'https://job-boards.greenhouse.io/isomorphiclabs', Scrapers.GREENHOUSE.value, 'https://www.isomorphiclabs.com'),
        CompanyItem("far.ai", "https://jobs.ashbyhq.com/far.ai", Scrapers.ASHBYHQ.value, "https://far.ai"),
        CompanyItem("cognition", "https://jobs.ashbyhq.com/cognition", Scrapers.ASHBYHQ.value, "https://cognition.ai"),
        CompanyItem("leonardo.ai", "https://jobs.ashbyhq.com/leonardo.ai", Scrapers.ASHBYHQ.value, "https://leonardo.ai"),
        CompanyItem("harvey", "https://jobs.ashbyhq.com/harvey", Scrapers.ASHBYHQ.value, "https://www.harvey.ai"),
        CompanyItem("ambient.ai", "https://jobs.ashbyhq.com/ambient.ai", Scrapers.ASHBYHQ.value, "https://www.ambient.ai"),
        CompanyItem("shieldai", "https://jobs.lever.co/shieldai", Scrapers.LEVER.value, "https://shield.ai"),
        CompanyItem('polyai', 'https://job-boards.greenhouse.io/polyai', Scrapers.GREENHOUSE.value, 'https://www.poly.ai'),
        CompanyItem('cleoai', 'https://job-boards.greenhouse.io/cleoai', Scrapers.GREENHOUSE.value, 'https://web.meetcleo.com'),
        CompanyItem('glean', 'https://job-boards.greenhouse.io/gleanwork', Scrapers.GREENHOUSE.value, 'https://www.glean.com'),
        CompanyItem("dust", "https://jobs.ashbyhq.com/dust", Scrapers.ASHBYHQ.value, "https://dust.tt"),
        CompanyItem("console", "https://jobs.ashbyhq.com/console", Scrapers.ASHBYHQ.value, "https://www.console.com"),
        CompanyItem("rivr", "https://jobs.lever.co/rivr", Scrapers.LEVER.value, "https://www.rivr.ai"),
        CompanyItem("anybotics", "https://jobs.lever.co/anybotics", Scrapers.LEVER.value, "https://www.anybotics.com"),
        CompanyItem("harrison", "https://jobs.ashbyhq.com/Harrison.ai", Scrapers.ASHBYHQ.value, "https://www.harrison.ai"),
        CompanyItem('aperaai', 'https://job-boards.greenhouse.io/aperaaiinc', Scrapers.GREENHOUSE.value, 'https://apera.ai'),
        CompanyItem('hoppr', 'https://job-boards.greenhouse.io/hoppr', Scrapers.GREENHOUSE.value, 'https://www.hoppr.ai'),
        CompanyItem("replit", "https://jobs.ashbyhq.com/replit", Scrapers.ASHBYHQ.value, "https://www.replit.com"),
        CompanyItem("multiverse", "https://jobs.ashbyhq.com/multiverse", Scrapers.ASHBYHQ.value, "https://www.multiverse.io"),
        CompanyItem('workato', 'https://job-boards.greenhouse.io/workato', Scrapers.GREENHOUSE.value, 'https://www.workato.com'),
        CompanyItem('enjins', 'https://apply.workable.com/enjins/#jobs', Scrapers.WORKABLE.value, 'https://www.enjins.com'),
        CompanyItem('cerebras.ai', 'https://job-boards.greenhouse.io/cerebrassystems', Scrapers.GREENHOUSE.value, 'https://www.cerebras.ai'),
        CompanyItem("limitless.ai", "https://jobs.ashbyhq.com/limitless", Scrapers.ASHBYHQ.value, "https://limitless.ai"),
        CompanyItem("openrouter.ai", "https://jobs.ashbyhq.com/openrouter", Scrapers.ASHBYHQ.value, "https://openrouter.ai"),
        CompanyItem("cradle.bio", "https://jobs.ashbyhq.com/cradlebio", Scrapers.ASHBYHQ.value, "https://www.cradle.bio"),
        CompanyItem("julius.ai", "https://jobs.ashbyhq.com/julius", Scrapers.ASHBYHQ.value, "https://www.julius.ai"),
        CompanyItem('vectara.com', 'https://job-boards.greenhouse.io/vectara', Scrapers.GREENHOUSE.value, 'https://www.vectara.com'),
    ]
