
from src.company_item import CompanyItem
from src.scrapers import Scrapers


def get_company_list() -> list[CompanyItem]:
    return [
        CompanyItem("base", "https://www.base.org/jobs", Scrapers.BASE, "https://www.base.org"),
        CompanyItem('Numeus', 'https://job-boards.eu.greenhouse.io/numus', Scrapers.GREENHOUSE, 'https://classic.numeus.xyz'),
        CompanyItem("kraken", "https://jobs.ashbyhq.com/kraken.com", Scrapers.ASHBYHQ, "https://kraken.com"),
        CompanyItem('fireblocks', 'https://job-boards.greenhouse.io/fireblocks', Scrapers.GREENHOUSE, 'https://www.fireblocks.com'),
        CompanyItem('blockstream', 'https://jobs.ashbyhq.com/blockstream', Scrapers.ASHBYHQ, 'https://www.blockstream.com'),
        CompanyItem('swanbitcoin', 'https://job-boards.greenhouse.io/swanbitcoin', Scrapers.GREENHOUSE, 'https://www.swanbitcoin.com'),
        CompanyItem('moonpay', 'https://jobs.lever.co/moonpay', Scrapers.LEVER, 'https://www.moonpay.com'),
        CompanyItem('phantom', 'https://jobs.ashbyhq.com/phantom', Scrapers.ASHBYHQ, 'https://phantom.com'),
        CompanyItem("paxos", "https://www.paxos.com/jobs", Scrapers.PAXOS, "https://www.paxos.com"),
        CompanyItem("circle", "https://careers.circle.com/us/en/search-results", Scrapers.CIRCLE, "https://www.circle.com"),
        CompanyItem("robinhood", "https://careers.robinhood.com", Scrapers.ROBINHOOD, "https://www.robinhood.com"),
        CompanyItem("ninjatrader", "https://job-boards.greenhouse.io/ninjatrader", Scrapers.GREENHOUSE, "https://www.ninjatrader.com"),
        CompanyItem('arbitrumfoundation', 'https://jobs.lever.co/arbitrumfoundation', Scrapers.LEVER,
                    'https://arbitrum.foundation'),
        CompanyItem('aragon', 'https://jobs.lever.co/aragon', Scrapers.LEVER, 'https://aragon.org'),
        CompanyItem('nomina.io', 'https://job-boards.greenhouse.io/nomina', Scrapers.GREENHOUSE,
                    'https://www.nomina.io'),
        CompanyItem('nomic.foundation', 'https://jobs.ashbyhq.com/nomic.foundation', Scrapers.ASHBYHQ,
                    'https://nomic.foundation'),
        CompanyItem("binance", "https://jobs.lever.co/binance", Scrapers.LEVER, "https://www.binance.com"),
        CompanyItem('ethglobal', 'https://jobs.ashbyhq.com/ethglobal', Scrapers.ASHBYHQ, 'https://ethglobal.com'),
        CompanyItem('li.fi', 'https://jobs.ashbyhq.com/li.fi', Scrapers.ASHBYHQ, 'https://li.fi'),
        CompanyItem('Caldera', 'https://jobs.ashbyhq.com/Caldera', Scrapers.ASHBYHQ, 'https://www.caldera.xyz'),
        CompanyItem('blox-route', 'https://jobs.lever.co/blox-route', Scrapers.LEVER,
                    'https://bloxroute.com'),
        CompanyItem('sprucesystems', 'https://jobs.lever.co/sprucesystems', Scrapers.LEVER, 'https://spruceid.com'),
        CompanyItem("scroll", "https://job-boards.greenhouse.io/scrollio", Scrapers.GREENHOUSE,
                    "https://scroll.io"),
        CompanyItem('impossiblecloud', 'https://jobs.lever.co/impossiblecloud', Scrapers.LEVER,
                    'https://www.impossiblecloud.com'),
        CompanyItem('ether-fi', 'https://jobs.ashbyhq.com/ether.fi', Scrapers.ASHBYHQ, 'https://www.ether.fi'),
        CompanyItem('fuellabs', 'https://jobs.lever.co/fuellabs', Scrapers.LEVER, 'https://www.fuel.network'),
        CompanyItem('harmony', 'https://jobs.lever.co/harmony', Scrapers.LEVER, 'https://www.harmony.one'),
        CompanyItem('wintermute', 'https://jobs.lever.co/wintermute-trading', Scrapers.LEVER,
                    'https://www.wintermute.com'),
        CompanyItem('coinspaid', 'https://jobs.eu.lever.co/coinspaid', Scrapers.LEVER,
                    'https://coinspaid.com'),
        CompanyItem("kaiko", "https://jobs.eu.lever.co/kaiko", Scrapers.LEVER, "https://www.kaiko.com"),
        CompanyItem("swissborg", "https://jobs.lever.co/swissborg", Scrapers.LEVER, "https://swissborg.com"),
        CompanyItem("ethereumfoundation", "https://jobs.lever.co/ethereumfoundation", Scrapers.LEVER,
                    "https://ethereum.org"),
        CompanyItem("avara", "https://avara.xyz/careers", Scrapers.AVARA, "https://avara.xyz"),
        CompanyItem("crypto", "https://jobs.lever.co/crypto", Scrapers.LEVER, "https://crypto.com"),
        CompanyItem("Luxor", "https://jobs.ashbyhq.com/luxor", Scrapers.ASHBYHQ, "https://www.luxor.tech"),
        CompanyItem("anchorage", "https://jobs.lever.co/anchorage", Scrapers.LEVER, "https://www.anchorage.com"),
        CompanyItem("Polygon", "https://jobs.ashbyhq.com/polygon-labs", Scrapers.ASHBYHQ, "https://polygon.technology"),
        CompanyItem('centrifuge', 'https://jobs.lever.co/centrifuge', Scrapers.LEVER, 'https://centrifuge.io'),
        CompanyItem("tokenmetrics", "https://jobs.lever.co/tokenmetrics", Scrapers.LEVER,
                    "https://www.tokenmetrics.com"),
        CompanyItem("offchainlabs", "https://jobs.lever.co/offchainlabs", Scrapers.LEVER,
                    "https://offchainlabs.com"),
        CompanyItem('recall', 'https://job-boards.greenhouse.io/recall', Scrapers.GREENHOUSE, 'https://recall.network'),
        CompanyItem("eiger", "https://boards.eu.greenhouse.io/eiger", Scrapers.GREENHOUSE,
                    "https://www.eiger.co"),
        CompanyItem('risklabs', 'https://jobs.ashbyhq.com/risklabs', Scrapers.ASHBYHQ, 'https://risklabs.foundation'),
        CompanyItem('celestia', 'https://jobs.lever.co/celestia', Scrapers.LEVER, 'https://celestia.org'),
        CompanyItem('gauntlet', 'https://jobs.lever.co/gauntlet', Scrapers.LEVER, 'https://gauntlet.network'),
        CompanyItem('gate.io', 'https://jobs.lever.co/gate', Scrapers.LEVER, 'https://gate.io'),
        CompanyItem('auroralabs', 'https://jobs.lever.co/aurora-dev', Scrapers.LEVER, 'https://auroralabs.dev'),
        CompanyItem("immutable", "https://jobs.lever.co/immutable", Scrapers.LEVER, "https://www.immutable.com"),
        CompanyItem("cere-network", "https://jobs.lever.co/cere-network", Scrapers.LEVER, "https://cere.network"),
        CompanyItem('cryptio', 'https://jobs.ashbyhq.com/cryptio', Scrapers.ASHBYHQ, 'https://cryptio.co'),
        CompanyItem('matterlabs', 'https://jobs.ashbyhq.com/matter-labs', Scrapers.ASHBYHQ, 'https://matter-labs.io'),
        CompanyItem("iftother", "https://boards.greenhouse.io/iftother", Scrapers.GREENHOUSE,
                    "https://free.technology"),
        CompanyItem("figure", "https://job-boards.greenhouse.io/figure", Scrapers.GREENHOUSE,
                    "https://www.figure.com"),
        CompanyItem("wyndlabs", "https://boards.greenhouse.io/wyndlabs", Scrapers.GREENHOUSE,
                    "https://www.wyndlabs.ai"),
        CompanyItem('animocabrands', 'https://jobs.lever.co/animocabrands', Scrapers.LEVER,
                    'https://www.animocabrands.com'),
        CompanyItem('toku', 'https://jobs.lever.co/toku', Scrapers.LEVER, 'https://www.toku.com'),
        CompanyItem("hiro", "https://boards.greenhouse.io/hiro", Scrapers.GREENHOUSE, "https://www.hiro.so"),
        CompanyItem('plume', 'https://jobs.ashbyhq.com/plume-network', Scrapers.ASHBYHQ, 'https://plume.org'),
        CompanyItem('coingecko', 'https://jobs.lever.co/coingecko', Scrapers.LEVER,
                    'https://www.coingecko.com'),
        CompanyItem('connext-network', 'https://jobs.lever.co/connext-network', Scrapers.LEVER,
                    'https://www.connext.network'),
        CompanyItem('ethenalabs', 'https://jobs.lever.co/ethenalabs', Scrapers.LEVER,
                    'https://www.ethena.fi'),
        CompanyItem('SeiLabs', 'https://jobs.ashbyhq.com/sei-labs', Scrapers.ASHBYHQ,
                    'https://www.sei.io'),
        CompanyItem('theblock', 'https://jobs.lever.co/theblockcrypto', Scrapers.LEVER,
                    'https://www.theblock.co'),
        CompanyItem('bitwise', 'https://jobs.lever.co/bitwiseinvestments', Scrapers.LEVER,
                    'https://bitwiseinvestments.com'),
        CompanyItem('grayscaleinvestments', 'https://boards.greenhouse.io/grayscaleinvestments', Scrapers.GREENHOUSE,
                    'https://grayscale.com'),
        CompanyItem('ssv.network', 'https://boards.greenhouse.io/bloxstaking', Scrapers.GREENHOUSE,
                    'https://ssv.network'),
        CompanyItem('xlabs', 'https://jobs.ashbyhq.com/Xlabs', Scrapers.ASHBYHQ,
                    'https://www.xlabs.xyz'),
        CompanyItem('orca', 'https://jobs.ashbyhq.com/orca', Scrapers.ASHBYHQ, 'https://www.orca.so'),
        CompanyItem('succinct', 'https://jobs.ashbyhq.com/succinct', Scrapers.ASHBYHQ, 'https://succinct.xyz'),
        CompanyItem("jumpcrypto", "https://boards.greenhouse.io/jumpcrypto", Scrapers.GREENHOUSE,
                    "https://jumpcrypto.com"),
        CompanyItem("0x", "https://jobs.ashbyhq.com/0x", Scrapers.ASHBYHQ, "https://0x.org"),
        CompanyItem("ritual", "https://boards.greenhouse.io/ritual", Scrapers.GREENHOUSE,
                    "https://ritual.net"),
        CompanyItem("coinmarketcap", "https://jobs.lever.co/coinmarketcap",
                    Scrapers.LEVER, "https://coinmarketcap.com"),
        CompanyItem('orderlynetwork', 'https://job-boards.greenhouse.io/orderly', Scrapers.GREENHOUSE,
                    'https://orderly.network'),
        CompanyItem('shardeum', 'https://boards.greenhouse.io/shardeumfoundation', Scrapers.GREENHOUSE,
                    'https://shardeum.org'),
        CompanyItem("zora", "https://boards.greenhouse.io/zora", Scrapers.GREENHOUSE, "https://zora.co"),
        CompanyItem("wormholefoundation", "https://boards.greenhouse.io/iftother", Scrapers.GREENHOUSE,
                    "https://wormhole.com"),
        CompanyItem("blockchain", "https://boards.greenhouse.io/blockchain", Scrapers.GREENHOUSE,
                    "https://www.blockchain.com"),
        CompanyItem("OKX", "https://boards.greenhouse.io/OKX", Scrapers.GREENHOUSE, "https://okx.com"),
        CompanyItem("bitmex", "https://boards.greenhouse.io/bitmex", Scrapers.GREENHOUSE, "https://bitmex.com"),
        CompanyItem("bitgo", "https://boards.greenhouse.io/bitgo", Scrapers.GREENHOUSE, "https://bitgo.com"),
        CompanyItem("bitpanda", "https://boards.eu.greenhouse.io/bitpanda", Scrapers.GREENHOUSE,
                    "https://bitpanda.com"),
        CompanyItem("uniswaplabs", "https://boards.greenhouse.io/uniswaplabs", Scrapers.GREENHOUSE,
                    "https://uniswap.org"),
        CompanyItem('osmosisdex', 'https://boards.greenhouse.io/osmosisdex', Scrapers.GREENHOUSE, 'https://osmosis.zone'),
        CompanyItem("figment", "https://boards.greenhouse.io/figment", Scrapers.GREENHOUSE,
                    "https://www.figment.io"),
        CompanyItem("OpenSea", "https://jobs.ashbyhq.com/OpenSea", Scrapers.ASHBYHQ, "https://opensea.io"),
        CompanyItem('center', 'https://jobs.ashbyhq.com/center', Scrapers.ASHBYHQ,
                    'https://center.app'),
        CompanyItem('linera.io', 'https://jobs.ashbyhq.com/linera.io', Scrapers.ASHBYHQ,
                    'https://linera.io'),
        CompanyItem('cointracker', 'https://jobs.ashbyhq.com/cointracker', Scrapers.ASHBYHQ,
                    'https://www.cointracker.io'),
        CompanyItem('Bastion', 'https://jobs.ashbyhq.com/Bastion', Scrapers.ASHBYHQ,
                    'https://www.bastion.com'),
        CompanyItem('Sui.Foundation', 'https://jobs.ashbyhq.com/Sui%20Foundation', Scrapers.ASHBYHQ,
                    'https://sui.io'),
        CompanyItem('dourolabs', 'https://jobs.ashbyhq.com/dourolabs.xyz', Scrapers.ASHBYHQ,
                    'https://dourolabs.xyz'),
        CompanyItem('rain', 'https://jobs.ashbyhq.com/rain', Scrapers.ASHBYHQ, 'https://www.raincards.xyz'),
        CompanyItem('mystenlabs', 'https://jobs.ashbyhq.com/mystenlabs', Scrapers.ASHBYHQ,
                    'https://mystenlabs.com'),
        CompanyItem('conduit', 'https://jobs.ashbyhq.com/Conduit', Scrapers.ASHBYHQ, 'https://conduit.xyz'),
        CompanyItem('kiln.fi', 'https://jobs.ashbyhq.com/kiln.fi', Scrapers.ASHBYHQ, 'https://www.kiln.fi'),
        CompanyItem("flashbots", "https://jobs.ashbyhq.com/flashbots.net", Scrapers.ASHBYHQ,
                    "https://www.flashbots.net"),
        CompanyItem('paradigm.xyz', 'https://jobs.ashbyhq.com/paradigm', Scrapers.ASHBYHQ, 'https://www.paradigm.xyz'),
        CompanyItem("solanafoundation", "https://jobs.ashbyhq.com/Solana%20Foundation", Scrapers.ASHBYHQ,
                    "https://solana.org"),
        CompanyItem('syndica', 'https://jobs.ashbyhq.com/syndica', Scrapers.ASHBYHQ, 'https://syndica.io'),
        CompanyItem('Blockworks', 'https://jobs.ashbyhq.com/Blockworks', Scrapers.ASHBYHQ,
                    'https://blockworks.co'),
        CompanyItem('ellipsislabs', 'https://jobs.ashbyhq.com/ellipsislabs', Scrapers.ASHBYHQ,
                    'https://ellipsislabs.xyz'),
        CompanyItem('safe.global', 'https://jobs.ashbyhq.com/safe.global', Scrapers.ASHBYHQ,
                    'https://safe.global'),
        CompanyItem('artemisanalytics', 'https://jobs.ashbyhq.com/artemisanalytics', Scrapers.ASHBYHQ,
                    'https://www.artemisanalytics.com'),
        CompanyItem('Keyrock', 'https://jobs.ashbyhq.com/Keyrock', Scrapers.ASHBYHQ,
                    'https://keyrock.eu'),
        CompanyItem('sound.xyz', 'https://jobs.ashbyhq.com/sound.xyz', Scrapers.ASHBYHQ,
                    'https://www.sound.xyz'),
        CompanyItem("quiknodeinc", "https://jobs.ashbyhq.com/quicknode", Scrapers.ASHBYHQ,
                    "https://www.quicknode.com"),
        CompanyItem('mara', 'https://job-boards.greenhouse.io/mara', Scrapers.GREENHOUSE,
                    'https://www.mara.com'),
        CompanyItem('xapo', 'https://boards.greenhouse.io/xapo61', Scrapers.GREENHOUSE,
                    'https://www.xapobank.com'),
        CompanyItem("exodus54", "https://job-boards.greenhouse.io/exodus54", Scrapers.GREENHOUSE,
                    "https://www.exodus.com"),
        CompanyItem("alchemy", "https://boards.greenhouse.io/alchemy", Scrapers.GREENHOUSE,
                    "https://www.alchemy.com"),
        CompanyItem("chainalysis", "https://jobs.ashbyhq.com/chainalysis-careers", Scrapers.ASHBYHQ,
                    "https://www.chainalysis.com"),
        CompanyItem("magiceden", "https://jobs.ashbyhq.com/magiceden", Scrapers.ASHBYHQ,
                    "https://www.magiceden.io"),
        CompanyItem('magic', 'https://job-boards.greenhouse.io/magic', Scrapers.GREENHOUSE, 'https://magic.link'),
        CompanyItem("aztec", "https://boards.eu.greenhouse.io/aztec", Scrapers.GREENHOUSE,
                    "https://aztec.network"),
        CompanyItem('near', 'https://job-boards.eu.greenhouse.io/nearfoundation', Scrapers.GREENHOUSE,
                    'https://near.org'),
        CompanyItem("nethermind", "https://jobs.ashbyhq.com/nethermind", Scrapers.ASHBYHQ,
                    "https://nethermind.io"),
        CompanyItem("dfinity", "https://boards.greenhouse.io/dfinity", Scrapers.GREENHOUSE, "https://dfinity.org"),
        CompanyItem('stellar', 'https://jobs.ashbyhq.com/stellar', Scrapers.ASHBYHQ, 'https://stellar.org'),
        CompanyItem('bitcoindepot', 'https://job-boards.greenhouse.io/bitcoindepot', Scrapers.GREENHOUSE, 'https://bitcoindepot.com'),
        CompanyItem("parity.io", "https://jobs.ashbyhq.com/parity", Scrapers.ASHBYHQ, "https://www.parity.io"),
        CompanyItem("oplabs", "https://jobs.ashbyhq.com/oplabs", Scrapers.ASHBYHQ, "https://www.oplabs.co"),
        CompanyItem('walletconnect', 'https://apply.workable.com/walletconnect', Scrapers.WORKABLE,
                    'https://reown.com'),
        CompanyItem('io-global', 'https://apply.workable.com/io-global/#jobs', Scrapers.WORKABLE,
                    'https://iohk.io'),
        CompanyItem('o1labs', 'https://boards.greenhouse.io/o1labs', Scrapers.GREENHOUSE, 'https://o1labs.org'),
        CompanyItem('paradigm.co', 'https://careers.kula.ai/paradigm', Scrapers.KULA, 'https://www.paradigm.co'),
        CompanyItem("Swissquote", "https://careers.smartrecruiters.com/Swissquote", Scrapers.SMARTRECRUITERS,
                    "https://en.swissquote.com"),
        CompanyItem('taxbit', 'https://boards.greenhouse.io/taxbit', Scrapers.GREENHOUSE, 'https://taxbit.com'),
        CompanyItem("avalabs", "https://boards.greenhouse.io/avalabs", Scrapers.GREENHOUSE,
                    "https://www.avalabs.org"),
        CompanyItem("aptoslabs", "https://boards.greenhouse.io/aptoslabs", Scrapers.GREENHOUSE,
                    "https://aptoslabs.com"),
        CompanyItem('almanak', 'https://apply.workable.com/almanak-blockchain-labs-ag', Scrapers.WORKABLE,
                    'https://almanak.co'),
        CompanyItem('dune', 'https://jobs.ashbyhq.com/dune', Scrapers.ASHBYHQ, 'https://dune.com'),
        CompanyItem('windranger', 'https://jobs.ashbyhq.com/windranger', Scrapers.ASHBYHQ,
                    'https://windranger.io'),
        CompanyItem('foundrydigital', 'https://boards.greenhouse.io/foundrydigital', Scrapers.GREENHOUSE,
                    'https://foundrydigital.com'),
        CompanyItem('immunefi', 'https://boards.greenhouse.io/immunefi', Scrapers.GREENHOUSE, 'https://immunefi.com'),
        CompanyItem('strike.me', 'https://boards.greenhouse.io/strike', Scrapers.GREENHOUSE, 'https://strike.me'),
        CompanyItem("serotonin", "https://jobs.lever.co/serotonin", Scrapers.LEVER, "https://serotonin.co"),
        CompanyItem("Decentraland", "https://jobs.lever.co/Decentraland", Scrapers.LEVER, "https://decentraland.org"),
        CompanyItem("copperco", "https://boards.eu.greenhouse.io/copperco", Scrapers.GREENHOUSE,
                    "https://copper.co"),
        CompanyItem("layerzerolabs", "https://boards.greenhouse.io/layerzerolabs", Scrapers.GREENHOUSE,
                    "https://layerzero.network"),
        CompanyItem("oasisnetwork", "https://boards.greenhouse.io/oasisnetwork", Scrapers.GREENHOUSE,
                    "https://oasisprotocol.org"),
        CompanyItem("ripple", "https://ripple.com/careers/all-jobs", Scrapers.RIPPLE, "https://ripple.com"),
        CompanyItem("eigenlabs", "https://jobs.ashbyhq.com/eigen-labs", Scrapers.ASHBYHQ,
                    "https://www.eigencloud.xyz"),
        CompanyItem("galaxydigital", "https://boards.greenhouse.io/galaxydigitalservices",
                    Scrapers.GREENHOUSE, "https://www.galaxy.com"),
        CompanyItem("clearmatics", "https://job-boards.greenhouse.io/clearmatics", Scrapers.GREENHOUSE,
                    "https://www.clearmatics.com"),
        CompanyItem('brave', 'https://job-boards.greenhouse.io/brave', Scrapers.GREENHOUSE,
                    'https://brave.com'),
        CompanyItem('zetachain', 'https://job-boards.greenhouse.io/zetachain', Scrapers.GREENHOUSE,
                    'https://www.zetachain.com'),
        CompanyItem('coinbase', 'https://www.coinbase.com/careers/positions', Scrapers.COINBASE, 'https://coinbase.com'),
        CompanyItem('sygnum', 'https://www.sygnum.com/careers-portal', Scrapers.SYGNUM, 'https://www.sygnum.com'),
        CompanyItem('lmax', 'https://careers.lmax.com/job-openings', Scrapers.LMAX, 'https://www.lmax.com'),
        CompanyItem("Saharaai", "https://jobs.ashbyhq.com/Sahara", Scrapers.ASHBYHQ,
                    "https://saharaai.com"),
        CompanyItem("symbiotic.fi", "https://jobs.ashbyhq.com/Symbiotic", Scrapers.ASHBYHQ,
                    "https://symbiotic.fi"),
        CompanyItem('noble', 'https://job-boards.greenhouse.io/noble', Scrapers.GREENHOUSE,
                    'https://www.noble.xyz'),
        CompanyItem("ramp.network", "https://job-boards.eu.greenhouse.io/rampnetwork", Scrapers.GREENHOUSE,
                    "https://ramp.network"),
        CompanyItem("RWA.xyz", "https://jobs.ashbyhq.com/RWA.xyz", Scrapers.ASHBYHQ,
                    "https://rwa.xyz"),
        CompanyItem('dragonflycapital', 'https://jobs.gem.com/dragonfly-careers', Scrapers.GEM,
                'https://www.dragonfly.xyz'),
        CompanyItem("BitcoinSuisse", "https://bitcoin-suisse.onlyfy.jobs", Scrapers.BITCOINSUISSE,
                    "https://bitcoinsuisse.com"),
        CompanyItem("gemini", "https://www.gemini.com/careers", Scrapers.GEMINI, "https://www.gemini.com"),
        CompanyItem("worldcoin", "https://world.org/careers", Scrapers.WORLDCOIN, "https://world.org"),
        CompanyItem("solana", "https://job-boards.greenhouse.io/solana", Scrapers.GREENHOUSE,
                    "https://solana.com"),
        CompanyItem('ondo-finance', 'https://jobs.gem.com/ondo-finance', Scrapers.GEM, 'https://ondo.finance'),
        CompanyItem('trojan-trading', 'https://jobs.gem.com/trojan-trading', Scrapers.GEM, 'https://trojan.com'),
        CompanyItem('cow-dao', 'https://jobs.ashbyhq.com/cow-dao', Scrapers.ASHBYHQ, 'https://cow.fi'),
        CompanyItem("bvnk", "https://job-boards.greenhouse.io/bvnk", Scrapers.GREENHOUSE,
                    "https://bvnk.com"),
        CompanyItem("meshpay", "https://job-boards.greenhouse.io/mesh", Scrapers.GREENHOUSE,
                    "https://meshpay.com"),
        CompanyItem("aPriori", "https://job-boards.greenhouse.io/apr", Scrapers.GREENHOUSE,
                    "https://www.apr.io"),
        CompanyItem('blockdaemon', 'https://jobs.ashbyhq.com/blockdaemon', Scrapers.ASHBYHQ, 'https://blockdaemon.com'),
        CompanyItem('chainlink-labs', 'https://jobs.ashbyhq.com/chainlink-labs', Scrapers.ASHBYHQ, 'https://chainlinklabs.com'),
        CompanyItem('block-labs', 'https://jobs.ashbyhq.com/block-labs', Scrapers.ASHBYHQ, 'https://www.blocklabs.io'),
        CompanyItem("asterdex", "https://jobs.lever.co/pioneer-services", Scrapers.LEVER, "https://www.asterdex.com/en"),
        CompanyItem('freedx', 'https://apply.workable.com/freedx/#jobs', Scrapers.WORKABLE,
                'https://www.exchange.freedx.com/en'),
        CompanyItem('trust-wallet', 'https://jobs.ashbyhq.com/trust-wallet', Scrapers.ASHBYHQ, 'https://trustwallet.com'),
        CompanyItem("cosmoslabs", "https://job-boards.greenhouse.io/cosmoslabs", Scrapers.GREENHOUSE,
                    "https://www.cosmoslabs.io"),
        CompanyItem("consensys", "https://consensys.io/open-roles", Scrapers.CONSENSYS,
                    "https://consensys.io"),
        CompanyItem("bitfinex", "https://bitfinex.recruitee.com", Scrapers.RECRUITEE, "https://www.bitfinex.com"),
    ]
