name: Run Crawler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler.py
        run: python crawler.py

      - name: Run write_jobs_age.py
        run: python write_jobs_age.py

      - name: Run get_new_jobs.py
        run: python get_new_jobs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update data via crawler.py [automated]'
          base: main
          branch: 'auto/crawler-update'
          title: 'Automated update from crawler.py'
          body: 'This PR contains changes made by running crawler.py via GitHub Actions.'
          delete-branch: true
          reviewers: yury-dubinin
