name: Run Crawler Crypto

on:
  schedule:
    - cron: '0 8 * * 2,6'
  workflow_dispatch:

jobs:
  run-crawler:
    uses: ./.github/workflows/reusable-crawler-run.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_names: 'crypto_crawler.py'
      output_json: 'crypto_current_jobs_mix.json'
      branch_name: 'auto/crawler-update'
      pr_title: 'Automated update from crawler.py'
