name: Run Crawler AI Greenhouse

on:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler_ai_greenhouse.py
        run: python crawler_ai_greenhouse.py

      - name: set-output
        if: failure() || success()
        id: set-output
        run: |
          ls -l
          echo "current=$(jq -c . ai_current_jobs_greenhouse.json)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update data via crawler_ai_greenhouse.py [automated]'
          base: main
          branch: 'auto/crawler-ai-greenhouse-update'
          title: 'Automated update from crawler_ai_greenhouse.py'
          body: |
            This PR contains changes made by running crawler_ai_greenhouse.py via GitHub Actions.

            ```json
            ${{ steps.set-output.outputs.current }}
            ```
          delete-branch: true
          reviewers: yury-dubinin
