name: Run Headed Crawler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-crawler:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          install-chromedriver: true

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler_headed.py
        run: python crawler_headed.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update data via crawler_headed.py [automated]'
          base: main
          branch: 'auto/crawler-headed-update'
          title: 'Automated update from crawler_headed.py'
          body: 'This PR contains changes made by running crawler_headed.py via GitHub Actions.'
          delete-branch: true
          reviewers: yury-dubinin
