name: Run Crawler Fintech Merge Jobs

on:
  workflow_dispatch:

jobs:
  run-crawler:
    uses: ./.github/workflows/reusable-crawler-run.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_names: 'merge_fin_jobs.py write_fin_jobs_age.py get_new_fin_jobs.py'
      output_json: 'fin_current.json'
      branch_name: 'auto/crawler-fintech-merge-jobs-update'
      pr_title: 'Automated update from merge_fin_jobs.py'
