name: Run All Crawler Crypto Workflows

on:
  schedule:
    - cron: '0 8 * * 2,6'
  workflow_dispatch:

jobs:
  crawler-crypto:
    uses: ./.github/workflows/crawler-crypto.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_name: crypto_crawler.py

  crawler-crypto-ashby:
    uses: ./.github/workflows/crawler-crypto.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_name: crypto_crawler_ashby.py

  crawler-crypto-greenhouse:
    uses: ./.github/workflows/crawler-crypto.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_name: crypto_crawler_greenhouse.py

  crawler-crypto-lever:
    uses: ./.github/workflows/crawler-crypto.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      script_name: crypto_crawler_lever.py
